version: '3.3'
services:
  mock-api:
    container_name: mock-api
    platform: linux/amd64
    image: wiremock/wiremock:3.3.1
    volumes:
      - ./mappings:/home/wiremock/mappings
    ports:
      - "9090:8080"
