version: '3.1'

networks:
  backend: 
    name: proxy-network
    driver: bridge

services:
  proxy-server:
    container_name: reverse-proxy
    image: local-reverse-proxy
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - PROXY_HTTP_PORT=80
      - DEFAULT_SERVER_IP=host.docker.internal
      - DEFAULT_SERVER_PORT=8080
      - ANOTHER_SERVER_IP=host.docker.internal
      - ANOTHER_SERVER_PORT=8081
      - ANOTHER_SERVER_PATH=/api/another
      - TZ=Asia/Seoul
