version: "3.1"

networks:
  backend:
    name: mariadb-network
    driver: bridge

services:
  db:
    image: mariadb:10.7
    container_name: mariadb
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    networks:
      - backend

  workbench:
    image: adminer:4.8.1
    container_name: mariadb-workbench
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - backend
